-- DropForeignKey
ALTER TABLE "OTP" DROP CONSTRAINT "OTP_userID_fkey";

-- AddForeignKey
ALTER TABLE "OTP" ADD CONSTRAINT "OTP_userID_fkey" FOREIGN KEY ("userID") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
